### ISSUE TITLE
Add Event Detail to Payment Receipt

### ISSUE THREAD

**Issue by monicabritton** [amschaal/django-ezreg#10]
I'm not sure if this is an Ezreg or Touchnet issue.  Currently the email sent from TouchNet does not specify which event was paid for.  It would be great if this information could be included in the email receipt, as some organizations require that for reimbursement.

Thanks,

Monica

**Comment by amschaal** [comment]
Event name, dates, address, and contact are in the email.  I'm assuming this is enough.

**Comment by monicabritton** [comment]
The original issue (#10 <https://github.com/amschaal/django-ezreg/issues/10>)
was raised due to a workshop registrant who needed an itemized receipt that
included the abbreviated credit card number (last 4 digits) AND the
names/dates of the workshop.  This was a requirement for reimbursement by
Mayo Clinic.

As it turns out he ended up cancelling his registration because he couldn't
attend the workshop after all, so never needed the detailed receipt.  No
one since has requested something similar.  It will be interesting to see
if people attending non-Bioinformatics Core events will request such.

Monica

Monica Britton
Sr. Bioinformatics Analyst
Genome Center and Bioinformatics Core Facility
University of California, Davis
mtbritton@ucdavis.edu
