### ISSUE TITLE
Search Across Events by Registration Date

### ISSUE THREAD

**Issue by monicabritton** [amschaal/django-ezreg#115]
I guess this is related to #40 .  It would be nice to be able to search by payment date.  For example, if I want to see a list of everyone who registered on 3/4 across events, that doesn't seem to be possible.

**Comment by amschaal** [comment]
It is possible on the registrations page, which is across events.  You need to select a start and end date, but you can accomplish the same thing.

**Comment by monicabritton** [comment]
I tried that and got nothing, so I thought it was searching the date of events.  Now I realize that I can't put the same date in both fields (e.g., search 3/4 - 3/4), I had to put different dates (3/4 - 3/5).  To me that is not obvious.  (But then, maybe that's just how I interpreted it?)

**Comment by amschaal** [comment]
Yes, you are right.  I will reopen this.  The dates should be clear which is inclusive and which is not.

**Comment by amschaal** [comment]
The second date is now inclusive.  The issue is that the time used for the date was set to 00:00:00, so it had to be overridden.
