### ISSUE TITLE
Revise "slug" help info

### ISSUE THREAD

**Issue by monicabritton** [amschaal/django-ezreg#122]
Currently the "Event Pages" tab, under slug, has "Enter the slug to be used in the URL".
Please add "Use only alphanumeric characters and underscores." (similar to main Event tab).

If an organizer tries to create an event page with a space in the slug and clicks save, the error message says: "Use only alphanumeric characters and underscores." which can confuse people.  (No, it wasn't me who tried this!)

**Comment by amschaal** [comment]
This is done, but error reporting should be better.  Created a new issue:
https://github.com/amschaal/django-ezreg/issues/123
