### ISSUE TITLE
"Amount" sort in "Registrations" -- How nulls are handled

### ISSUE THREAD

**Issue by monicabritton** [amschaal/django-ezreg#133]
Maybe I'm one of the few people who tries to sort on the "Amount" column in the (all) Registrations page, but the sorting is not convenient.  When I sort from low to high the lowest numerical value is at the top of the list.  But, when I sort from high to low, all the Nulls (absence of price, free events) are at the top.  I want to see the highest price at the top.

**Comment by amschaal** [comment]
And what if you want to see nulls first?  Unfortunately there are only 2 possible sort orders.  Someone will always have to work around this, so I'd suggest just paginating by 100 and clicking next page until you see a value.

**Comment by monicabritton** [comment]
Since Nulls equal zero payment, I would like to see them sorted as zeroes not as infinity (so they are next to the low prices not before the high prices).  But, I can cope...
