### ISSUE TITLE
Remove payment method requirement if Price is $0.00

### ISSUE THREAD

**Issue by lnszeto** [amschaal/django-ezreg#146]
![Capture](https://user-images.githubusercontent.com/59706175/72096406-0020f380-32cf-11ea-82a7-3034a6462d29.PNG)

If someone enters a coupon code which brings the price to $0.00, it would be nice to have the form automatically proceed to the next step. Currently, the individual needs to enter the coupon code and hit continue, which brings them back to the same step (image attached). The page refreshes showing the new $0.00 price option but then requires a payment method which is not very intuitive. It should allow the user to skip selecting a payment method.

**Comment by amschaal** [comment]
Thanks for the feedback.  The issue should be fixed.
