### ISSUE TITLE
Create more custom forms

### ISSUE THREAD

**Issue by amschaal** [amschaal/django-ezreg#153]
Want to capture  university, college, department.  Either:
- Create custom vocabularies (per organizer?), with that being a type of question.
OR
-Create ability to have custom form plugins, which are selectable.  This would allow for more complex form logic, etc.  However, it would also change registration export, etc.

**Comment by amschaal** [comment]
Keep it simple for now.  There will be a form with 4 fields added to the first registration page, including:
- Institution (UCD, Other UC, Other Academic, Government?, Other)
- Other institution (if not UC Davis)
- College / School (if UCD)
- Department (if UCD)

**Comment by PLNReynolds** [comment]
It would be GREAT if the College/School and Department (if UCD) could be a dropdown so I don't have to keep deciphering acronyms and spelling variants, and so we can do reporting both within and across training units. Get list from OR, check for updates periodically (annually)?

**Comment by amschaal** [comment]
There is now a department field on the first page of registration (with name and email).  It is configured to have the college abbreviation followed by the department stored with the registration.  For example, "COE: Chemical Engineering".  Hopefully all of the organizers don't mind having the department select, otherwise I'll have to add something in the event config to make it optional.
