### ISSUE TITLE
Cannot login to cancel registration

### ISSUE THREAD

**Issue by acgetchell** [amschaal/django-ezreg#158]
I get "Forbidden: Login failed" from:

https://registration.genomecenter.ucdavis.edu/accounts/login/?next=%2Fevents%2Fdatalab2020intropython%2F&ticket=ST-257883-dk-rgMmi9-ecn-I6Y4WhpiieWx4-casweb8

Also, that page is a dead end, there are no links to go anywhere else, and of course the back button attempts to re-submit the form.

**Comment by amschaal** [comment]
I'm not sure how you arrived at that link.  Usage of the registration system does not require authentication unless you are an organizer.

**Comment by acgetchell** [comment]
How do you unregister from a workshop?

**Comment by amschaal** [comment]
We don't currently allow users to unregister themselves.  You may contact
the event's organizer and request that they cancel your registration.
