### ISSUE TITLE
Genome Center missing in optgroup

### ISSUE THREAD

**Issue by tobigithub** [amschaal/django-ezreg#162]
Hi,
the Genome Center is an affiliated center within the CBS, therefore should be added in the drop-down menu when selecting a department for course registrations and others.

See: https://biology.ucdavis.edu/faculty/affiliated-centers-directory/genome-center

![image](https://user-images.githubusercontent.com/2569565/90432368-474e3e80-e07f-11ea-9001-91d722f8fdbf.png)

Source HTML: 

````
 <optgroup label="College of Biological Sciences"> <option value="CBS: Evolution and Ecology">Evolution and Ecology</option> <option value="CBS: Microbiology and Molecular Genetics">Microbiology and Molecular Genetics</option> <option value="CBS: Molecular and Cellular Biology">Molecular and Cellular Biology</option> <option value="CBS: Neurobiology, Physiology and Behavior">Neurobiology, Physiology and Behavior</option> <option value="CBS: Plant Biology">Plant Biology</option> </optgroup>
````
Cheers
Tobias

**Comment by amschaal** [comment]
Added it.

**Comment by tobigithub** [comment]
Thanks!
Tobias
