### ISSUE TITLE
Problem in step before payment processing

### ISSUE THREAD

**Issue by tobigithub** [amschaal/django-ezreg#163]
HI,
when using Chrome 84.x the payment selection (free/credit card) buttons do not toggle back. Both options are visually activated, that is of course bogus. Only one button should be activated at any given time. Happens, when selection option one, then two and then one again. 

![image](https://user-images.githubusercontent.com/2569565/90432961-f12dcb00-e07f-11ea-8ee2-3e32e66d22a5.png)

Best
Tobias

**Comment by amschaal** [comment]
The forms always processed properly, and ignored payment method if the price was ZERO.  However, this could be confusing still thinking a payment method is necessary when registration is free.  I added some javascript hackery to may this dynamically hide payment method if the price is ZERO.  I should put it into production sometime next week.
