### ISSUE TITLE
Dafis Payment Info not Exportable (and not on Confirmations)

### ISSUE THREAD

**Issue by monicabritton** [amschaal/django-ezreg#2]
I notice that the Dafis account/contact info isn't on the confirmations, so just exported the registration info and have two issues:
1) There doesn't seem to be a way to export the account number and accounting contact info.  This is a requirement, since I need to supply it to Sally & Gail.
2) I had to independently check each box for fields to export.  There should be a "Select All" box too.

Thanks in advance,

M

**Comment by amschaal** [comment]
Export has been redone and now exports payment information as well.  Additionally, groups of fields can be checked/unchecked by group.
