### ISSUE TITLE
Allow Organizer to customize Waitlist Registration email.

### ISSUE THREAD

**Issue by monicabritton** [amschaal/django-ezreg#20]
Currently, the email specifies 24 hours for time limit.  It would be nice to be able to change that.

Also, the current email says "You have been moved off of the waitlist for the event,"  I liked the previous wording, "It looks like a spot has opened up for the event you previously waitlisted,"

The old version also included "If you are no longer interested in attending, please respond to the email so that we may open up the spot to the next waitlisted person."  That might be nice to add too.

Thanks!

**Comment by amschaal** [comment]
Add a cancellation link so they can cancel themselves instead of notifying the organizer.

**Comment by monicabritton** [comment]
I would like to re-open this issue for a different reason, specifically:
**Is it possible to add a customizable sentence to registration confirmation emails?**

Why do I want to do this:
We often get emails asking for general workshop information (such as lodging, etc.) that is easily accessible via our website (http://bioinformatics.ucdavis.edu/training/).  And, we seem to be getting such emails with greater frequency now than in the past.  I think that is because many folks go through the registration site, pay and get their confirmation without ever noticing the subtle reference to our web site at the bottom of the first page.

So, I would like to be able to add a sentence referencing our website to the confirmation emails.  I think that other groups might like this feature as well.

Thanks!

**Comment by monicabritton** [comment]
I would like to re-open this issue to address the first sentence in the original post:
"Currently, the email specifies 24 hours for time limit. It would be nice to be able to change that."

Maybe change that to be another customizable field in the "custom text" tab?
