### ISSUE TITLE
Non-standard characters import incorrectly into Excel

### ISSUE THREAD

**Issue by monicabritton** [amschaal/django-ezreg#26]
This is mostly to document, maybe not a true "issue".

When exporting csv and opening in Excel, the character "ø" becomes "Ã¸".

However, if I open the csv in a text editor, copy the "ø" and paste, it shows correctly as "ø" in Excel.

(Here's hoping that github doesn't change the characters when I post this.)

**Comment by amschaal** [comment]
Also, added support for xls and xlsx
