### ISSUE TITLE
Payment Modification

### ISSUE THREAD

**Issue by monicabritton** [amschaal/django-ezreg#3]
We need to be able to modify the payment amount (for cancellations or errors or other reasons).  Really, we need to be able to modify everything!  (Except credit card numbers, which aren't in this system anyway.)

Thanks!

M

**Comment by amschaal** [comment]
Prices and payment information (except offsite, such as for credit cards) are now modifiable.  The caveat is that registrations that have already been marked as paid may not be modified.  I'll likely add some sort of refund functionality to address any price change after payment has been made.
