### ISSUE TITLE
Admin register - add notes 

### ISSUE THREAD

**Issue by brooksph** [amschaal/django-ezreg#38]
We have several registration options for housing and I'd like to admin register some folks that we've decided to waive costs for. Currently when I admin register I can't make a price selection, which makes sense, but our prices are tied to specific time periods for housing. Is it possible to make comments when I admin register so I can keep track the time period participants are registered for?

**Comment by amschaal** [comment]
There is now a field on the first page of registration when you use the admin registration functionality.  You can also add notes when modifying a registration.  Any admin notes will be added to the registration export.
