### ISSUE TITLE
Add column to registration output 

### ISSUE THREAD

**Issue by brooksph** [amschaal/django-ezreg#39]
We have several housing registration options for different dates but with identical prices. Can you add a column containing the selected option so I know which dates were chosen?

**Comment by amschaal** [comment]
Is the name of the price sufficient, or do you need the description?  When exporting, "Amount" is the dollar price, and "Price" is actually the name of the price.

**Comment by brooksph** [comment]
The name of the price is sufficient

**Comment by amschaal** [comment]
Okay, closing.
