### ISSUE TITLE
Admin register - requires payment

### ISSUE THREAD

**Issue by brooksph** [amschaal/django-ezreg#41]
The current behavior allows me to select the price option which I like for record keeping purposes but requires that I pay. Prior to this change I was able to admin register without pay and that's what I'd like to be able to do.

**Comment by amschaal** [comment]
Strange, the price doesn't show up when I do it.  Are you using "Register -> Admin register" from the event management page?  If that isn't working, please email me a link to the management page.

**Comment by brooksph** [comment]
I cleared the pending registrations and it worked. Not sure what happened. I think I tried to register them before so the system may have been confused by a pending registration with same e-mail. Thanks!
