### ISSUE TITLE
Add Payment Status for Admin Registration

### ISSUE THREAD

**Issue by monicabritton** [amschaal/django-ezreg#46]
Currently, the payment status is blank when I do an Admin registration.  This doesn't allow for the payment status to be set, even if I try to modify. I would like to:
A) Be able to set to an existing payment status (e.g., "Paid" or "Pending")
B) Add a new payment status ("freebee" or such), so I can filter for them.

Thanks!

**Comment by amschaal** [comment]
The point of the admin register was basically to bypass the payment step.  Without any payment, there is nothing to modify.

If a payment is involved, registration should be done the normal way.  Nothing will keep an admin from following the normal process that a user would.  And admin can always go in and change the payment status after they go through the normal registration process.

Closing this unless these 2 workflows don't cover all the necessary use cases.
