### ISSUE TITLE
How to Insert Image without URL?

### ISSUE THREAD

**Issue by monicabritton** [amschaal/django-ezreg#53]
In the "Body" box tools, there is one for "Insert/Edit Image".  Upon clicking, the resulting dialog box wants an "Image URL".  Do I have to upload the image to someplace just to link it?  Shouldn't there be a way to actually insert the image itself?

Thanks!

**Comment by amschaal** [comment]
Related to #70.  The question is, do we support file uploads, or do we expect the user to upload elsewhere, and link from the registration system.

**Comment by amschaal** [comment]
Closing this, but leaving #70 open for now.  As you say, an image needs to be uploaded somewhere web accessible.  You can accomplish this with dropbox or similar, but the question is should we support it within the app?
