### ISSUE TITLE
Add "*Required Field" to bottom of pages

### ISSUE THREAD

**Issue by monicabritton** [amschaal/django-ezreg#57]
Required fields have an "\*" (such as Email\*), but seems like there should be at the bottom of each of these pages:

*Required field

**Comment by amschaal** [comment]
I added this to the bottom of forms, only to realize that not all forms would have required fields.  Unfortunately, it would take far too much code to determine if any forms shown on the page have required fields.  I'm going to just hope people figure out what it means.  If they don't, they will know which ones are required on submit!
