### ISSUE TITLE
Refund doesn't show as such in export

### ISSUE THREAD

**Issue by monicabritton** [amschaal/django-ezreg#59]
When someone gets a refund, I update their status to "cancelled", then modify payment to put the amount under "Refunded".  (The payment status still shows "Paid").  

On the "Registrations" page, under Amount it shows the amount originally paid and the amount refunded, but if I export this record, the XLSX only shows the original Amount, not the net, or refunded amount.  

Actually, I notice that even if people cancel themselves (or cancel during registration, by not completing payment?) the Amount still shows, both on the registration site and in the export, even though they didn't pay.  Should an amount be shown for such cancelled people?

(This may not make sense the way I wrote it.)

**Comment by amschaal** [comment]
I'll take a look.  It seems like in the export, the best thing would be to show amount paid, and amount refunded, that way no information is lost.  I'll see if I can make the interface more clear too.
