### ISSUE TITLE
add a customizable sentence to registration confirmation emails

### ISSUE THREAD

**Issue by monicabritton** [amschaal/django-ezreg#63]
This was a comment to issue #20, to which it is somewhat tangential, and was never addressed. I am bringing it up again because I noticed that there is nothing in the registration email that tells a person where they registered (e.g., the registration site URL) or where they can go for more info. Since people often register months in advance (and are sometimes admin-registered), this is important.

We often get emails asking for general workshop information (such as lodging, etc.) that is easily accessible via our website (http://bioinformatics.ucdavis.edu/training/). And, we seem to be getting such emails with greater frequency now than in the past. I think that is because many folks go through the registration site, pay and get their confirmation without ever noticing the subtle reference to our web site at the bottom of the first page.

So, I would like to be able to add a sentence referencing our website to the confirmation emails. I think that other groups might like this feature as well.

Thanks!

**Comment by amschaal** [comment]
You can now do this under the "Custom Text" tab.  Just add your HTML content to the "Registration Email" WSIWYG.
