### ISSUE TITLE
bcc email address "changes" when event is copied

### ISSUE THREAD

**Issue by monicabritton** [amschaal/django-ezreg#65]
In the original event the  bcc is mtbritton@ucdavis.edu

When the event is copied, it shows up as m,t,b,r,i,t,t,o,n,@,u,c,d,a,v,i,s,.,e,d,u

I have also seen this happen at other times (in addition to copy) and will edit this issue when I find such again.

**Comment by amschaal** [comment]
Thinking that this function may be the culprit:
https://github.com/amschaal/django-ezreg/blob/master/ezreg/fields.py#L23
