### ISSUE TITLE
Revise "Developed by" and contact info

### ISSUE THREAD

**Issue by monicabritton** [amschaal/django-ezreg#7]
To avoid unnecessary emails going to the Bioinformatics Core, I suggest two things:

1.  Include a specific field (preferably required) for organizer contact info

2. Either drop the "Developed by" line from the bottom of some of the internal pages (registration form, etc.) or revise the wording to make it clear that the registration engine was built by the Bioinformatics Core, but the event contact is not (necessarily) the BioCore.

Thanks,

Monica

**Comment by amschaal** [comment]
1.  I'm not sure it is necessary to add yet another field when such information is easily added in the event description.  I think it just adds more complexity and creates unnecessary restraints.

2.  I think Matt would like to keep some sort of obvious attribution.  How about "Software developed by the UC Davis Bioinformatics Core"?

**Comment by monicabritton** [comment]
Yes, attribution is needed.  I like "Software developed by the UC Davis Bioinformatics Core" with a link to our website and maybe also to this github page.

However, I still believe there needs to be a required field for event contact info.  I can't imagine an event that doesn't have someone to contact for questions.  It is extremely easy for even an experienced event coordinator to forget to include such information.  (Note that I made this an issue after we received a couple of emails about another Core's events because there wasn't any contact info.)

Thanks!
