### ISSUE TITLE
Send email when pending registration is cancelled due to time-out

### ISSUE THREAD

**Issue by monicabritton** [amschaal/django-ezreg#72]
Can system to set up to send potential registrants an email stating that their pending registration has been cancelled to due time-out/inactivity, and asking them to re-start if they still want to register.

We also discussed adding a chron job that would run at least a couple times per day to cancel pending registrations.

Thanks!

**Comment by amschaal** [comment]
The email seems unnecessary and is not something I think most people would expect to receive.  The cron job is a configuration issue, but the command to remove expired registrations already exists:
https://github.com/amschaal/django-ezreg/blob/master/ezreg/management/commands/delete_expired_registrations.py
