### ISSUE TITLE
Unable to fill in **Price** field when registering.

### ISSUE THREAD

**Issue by doctornerdis** [amschaal/django-ezreg#82]
I'm getting hung up when trying to register because the form tells me I need to put something in the **price** field. But I can't see where to enter the information. I'm trying to register for CarpentryCon + Housing.

Thanks!

![20180531030454](https://user-images.githubusercontent.com/16094430/40810952-3f580fb2-64e4-11e8-82d6-82e769e58948.png)

**Comment by monicabritton** [comment]
Hi DIBSI folks:

I intercepted this email (which I'm not sure any of you would see unless
you've subscribed to the registration github site).  I don't have
permissions to see exactly how you have set up this registration, but I did
a test registration, and got the same error as described below.

Do you require a coupon code for people to register for the "+ housing"? I
can see that several people have successfully registered with credit cards,
so I'm not sure what else could be leading to this error.

BTW, Adam Schaal is on vacation this week.

Thanks,

Monica

Monica Britton
Sr. Bioinformatics Analyst
Genome Center and Bioinformatics Core Facility
University of California, Davis
mtbritton@ucdavis.edu

**Comment by monicabritton** [comment]
Hi Karen:

You can also modify the "Open until" date on the Event definition page.  If
you change it to a date in the past, the "Register" button at the bottom of
the first screen will change to "Registration is closed for this event".

Thanks,

Monica

Monica Britton
Sr. Bioinformatics Analyst
Genome Center and Bioinformatics Core Facility
University of California, Davis
mtbritton@ucdavis.edu

**Comment by doctornerdis** [comment]
This is a little outside the purview of this issue, but would it be possible to have some suggestions of places to stay that'll be close to the conference? Actually, that would be a helpful addition to the website. It does say that registration goes through the 15th, so it would be helpful to clarify that folks coming from out of town now need to find their own housing.

**Comment by monicabritton** [comment]
Hi Nicholas:

Thank you for your feedback.  However, the addresses on these emails (via
github repo) are the people who write and maintain the registration
software, not the groups putting on the workshops.

I am copying dibsi.training@gmail.com, which is the correct email for any
questions related to the DIBSI summer workshops.

Best wishes,

Monica Britton
Sr. Bioinformatics Analyst
Genome Center and Bioinformatics Core Facility
University of California, Davis
mtbritton@ucdavis.edu

**Comment by doctornerdis** [comment]
Ah, got it. Many thanks, @monicabritton.
