### ISSUE TITLE
Library of Form Questions by Organizer

### ISSUE THREAD

**Issue by monicabritton** [amschaal/django-ezreg#83]
It would be great if each organizer could create a library of commonly-used questions to be included in the "Form".  Or, alternatively, to be able to copy just the Form from one Event to another!

**Comment by amschaal** [comment]
This has been working by allowing an organizer to copy questions from other events.

**Comment by monicabritton** [comment]
Just noticed something:  If I copy the form fields from another event, they are automatically saved in the new event. (I don't need to click on "Save").  Also, if I remove fields, they are also automatically saved.  Even if I add a new field, it is automatically saved.  

So, um, what does the "Save" button do?  (Or should there be an "Undo" button instead?)

**Comment by amschaal** [comment]
Are you sure?  Try selecting the questions from the dropdown.  They will populate the form, but they aren't saved yet.  REFRESH the whole page, don't switch tabs.  They shouldn't be there if you didn't save.

**Comment by monicabritton** [comment]
OK.  That's correct, but not necessarily intuitive ... file under "Monica problem" (not really a problem) unless someone else questions/comments.
