### ISSUE TITLE
Add option to not show registration button

### ISSUE THREAD

**Issue by monicabritton** [amschaal/django-ezreg#89]
Currently, at the bottom of the main registration page, it either shows "Register" (if open) or "Waitlist" (if full) or "Registration is Closed for this event".  I would like another option, to not show anything there.  

That way, I can use the main registration page as a "pass-through", with links to sub-registration pages, such as one accepting applications, one for full-workshop registration, one for lecture-only, etc.  This allows for the sub-registration pages to have their own waitlists, max capacities, etc.

Thanks!

**Comment by amschaal** [comment]
I've implemented this such that if you choose to advertise, but not activate the event, it will be advertised with nothing shown under status or closing date.  When you click on the event, it should show nothing about when it closes, or have any button for registration.  You will be able to, as you suggested, link other registration pages from the advertised, non-active event.
