### ISSUE TITLE
Successful Credit Card Registrations Showing as Cancelled

### ISSUE THREAD

**Issue by monicabritton** [amschaal/django-ezreg#9]
This issue appears to only be affecting Metabolomics Workshops. The registrant pays by credit card, the confirmation email is sent, but the registration site shows the payment and registration status as "cancelled". I was able to log into Touchnet and confirm the transactions. The only difference I can see between them is on the Touchnet side:  the Bioinformatics workshops are under "UC Davis Genome Center Bioinformatics Core Courses" and have FID of 006 (for our workshops) or FID=007 (for DNATech Core workshop).  The Metabolomics workshops have FID=009 and are under "Genome Center Registration".

Is it possible that the registration site isn't capturing the Touchnet return code correctly?

Thanks,

Monica

**Comment by amschaal** [comment]
With logging enabled, I have not been able to witness this issue.  I'm closing it so long as it doesn't come up again.
