### ISSUE TITLE
Add "application declined" status and email option

### ISSUE THREAD

**Issue by monicabritton** [amschaal/django-ezreg#90]
Currently, we can accept applications, by changing the status to "Accepted", and that generates an appropriate email.  

However, there is no corresponding status/email for people whose applications are not accepted (declined? denied?) other than "cancelled".  I don't think cancelled is appropriate at this point, and it will cause confusion. (Cancellation IS appropriate if someone who has been accepted doesn't complete their registration within the appropriate time period.)

It would be nicer if those whose applications are not accepted, could get an email with clear and polite wording, like "due to the high number of applications, we were not able to accept everyone".

It would even be better if the email could be customized to the event, so the denied applicant could be directed to other registration options (if appropriate).

thanks!

**Comment by amschaal** [comment]
An additional status has been added for denying applications.  An email may be sent to notify the user.  The email text can be overridden using the "Custom Text"  tab and entering something under "Application Denied Email".
