### ISSUE TITLE
need to know if someone uses coupon code and payment name

### ISSUE THREAD

**Issue by najoshi** [amschaal/django-ezreg#95]
We need to be able to know if someone used a coupon code in the registration table and also the payment name. E.g., another column for the coupon code that says "UC25" (or whatever it is) and a column for payment name that says "R only Industry/For Profit".

**Comment by amschaal** [comment]
Coupon code and price name are both now exported by default using the registration export (for exporting registrations across events).  Additionally, coupon code is added as a configurable export field when creating an export from the event management page.

Exports will be how you get all these minute details, as it is too much to display in the web interface.
